conf/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from fixtures.views import home_page

MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns = [
    # ADMIN / DEV
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),

    # PUBLIC
    path('', home_page, name="index"),
    path('movies/', include('fixtures.urls', namespace='fixtures')),

    # USER AUTH
    path('security/', include('security.urls', namespace='security')),
]
urlpatterns += MEDIA_FILE_PATHS

fixtures/urls.py
from django.urls import path

from fixtures.views import (
    MovieList, MovieDetail, TopMovies, UpdateVote, CreateVote, MovieImageUpload,
)

app_name = 'fixtures'
urlpatterns = [
    # Movie Views:
    path('movie',
         MovieList.as_view(),
         name='MovieList'),
    path('<int:pk>',
         MovieDetail.as_view(),
         name='MovieDetail'),
    path('top10/',
         TopMovies.as_view(),
         name='TopMovies'),


    # Vote Views
    path('<int:movie_id>/vote',
         CreateVote.as_view(),
         name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>',
         UpdateVote.as_view(),
         name='UpdateVote'),

    # Upload Views
    path('movie/<int:movie_id>/image/upload',
         MovieImageUpload.as_view(),
         name='MovieImageUpload'),

]

fixtures/models/movie.py
from django.db import models
from django.db.models.aggregates import (
    Sum
)

from .person import Person


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related(
            'writers', 'actors'
        )
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_sum=Sum('vote__value'))
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by('-vote_sum')
        qs = qs[:limit]
        return qs


# Create your models here.
class Movie(models.Model):
    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    NOT_RATED: int = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS: (int, str) = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audience'),
        (RATED_PG, 'PG - Parental Guidance Suggested'),
        (RATED_R, 'R - Restricted'),
    )
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)

    director = models.ForeignKey(
        to='Person',
        on_delete=models.SET_NULL,
        related_name='directed',
        null=True,
        blank=True
    )

    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True
    )

    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True
    )

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie',
                           'person',
                           'name')

fixtures/models/movie_image_upload.py
# Author - Matt Andrzejczuk
from uuid import uuid4

from django.conf import settings
from django.db import models


def movie_directory_path_with_uuid(instance, filename):
    return '{}/{}'.format(instance.movie_id, uuid4())


class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

fixtures/models/person.py
from django.db import models


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie'
        )


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died
            )
        return '{}, {} ({})'.format(
            self.last_name,
            self.first_name,
            self.born
        )

fixtures/models/vote.py
from django.conf import settings
from django.db import models

from .movie import Movie


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user
            )
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user
            )


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = ((UP, '👍🏻',),
                     (DOWN, '👎🏻',),)

    objects = VoteManager()

    value = models.SmallIntegerField(
        choices=VALUE_CHOICES,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    movie = models.ForeignKey(
        Movie,
        on_delete=models.SET_NULL,
        null=True
    )
    voted_on = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        unique_together = ('user', 'movie')

fixtures/forms/movie_img_upload_form.py
# Author - Matt Andrzejczuk
from django import forms
from django.contrib.auth import get_user_model

from fixtures.models import MovieImage, Movie


class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True
    )

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    class Meta:
        model = MovieImage
        fields = ('image', 'user', 'movie')

fixtures/forms/vote.py
from django import forms
from django.contrib.auth import get_user_model

from fixtures.models import Vote, Movie


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True,
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = (
            'value', 'user', 'movie',
        )

fixtures/forms/vote_form.py
from django import forms
from django.contrib.auth import get_user_model

from fixtures.models import Vote, Movie


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True,
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = (
            'value', 'user', 'movie',
        )

fixtures/views/base_views.py
# Author - Matt Andrzejczuk

# NO TEMPLATES:
from django.http import HttpResponse
from django.template import loader
# GENERIC:
from django.urls import reverse
from django.views.generic import (ListView, DetailView, )

from fixtures.forms import (VoteForm, MovieImageForm, )
from fixtures.mixins import CachePageVaryOnCookieMixin
from fixtures.models import (Movie, Vote, )

from pyink import ink




def home_page(request):
    template = loader.get_template("home_page.html")
    visitor = request.META
    context = {"visitor": visitor}
    return HttpResponse(template.render(context))


class MovieList(ListView):
    model = Movie
    paginate_by = 10
    # def get_context_data(self, object_list, **kwargs):
    #     ctx = super().get_context_data()
    #     ctx['user'] = self.request.user
    #     return ctx


class TopMovies(CachePageVaryOnCookieMixin, ListView):
    template_name = 'fixtures/top_movies_list.html'
    queryset = Movie.objects.top_movies(limit=10)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['user'] = self.request.user
        ink.p("TopMovies", ink.BG_PURPLE, ink.ENDC + "\n")
        return ctx

class MovieDetail(DetailView):
    queryset = (
        Movie.objects.all_with_related_persons_and_score()
    )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse(
                    'fixtures:UpdateVote',
                    kwargs={'movie_id': vote.movie.id,
                            'pk': vote.id}
                )
            else:
                vote_form_url = (
                    reverse(
                        'fixtures:CreateVote',
                        kwargs={'movie_id': self.object.id}
                    )
                )
            vote_form = VoteForm(instance=vote)
            image_form = self.movie_image_form()
            ctx['vote_form'] = vote_form
            ctx['image_form'] = image_form
            ctx['vote_form_url'] = vote_form_url
        return ctx

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None

fixtures/views/movie_upload_views.py
# Author - Matt Andrzejczukd
from django.contrib.auth.mixins import (
    LoginRequiredMixin
)
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView

from fixtures.forms import MovieImageForm


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse(
            'fixtures:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('fixtures:MovieDetail', kwargs={'pk': movie_id})
        return movie_detail_url

fixtures/views/movie_views.py
# Author - Matt Andrzejczuk
from django.urls import reverse
from django.views.generic import (ListView, DetailView, )

from fixtures.forms import (VoteForm, )
from fixtures.models import (Movie, Vote, )


class MovieList(ListView):
    model = Movie


class TopMovies(ListView):
    template_name = 'fixtures/top_movies_list.html'
    queryset = Movie.objects.top_movies(limit=10)

class MovieDetail(DetailView):
    queryset = (
        Movie.objects.all_with_related_persons_and_score()
    )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse(
                    'fixtures:UpdateVote',
                    kwargs={'movie_id': vote.movie.id,
                            'pk': vote.id}
                )
            else:
                vote_form_url = (
                    reverse(
                        'fixtures:CreateVote',
                        kwargs={'movie_id': self.object.id}
                    )
                )
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
        return ctx

fixtures/views/vote_views.py
# Author - Matt Andrzejczuk
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import (CreateView, )
from django.views.generic import (UpdateView, )

from fixtures.forms import VoteForm
from fixtures.models import (Vote, )


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs[
            'movie_id'
        ]
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'fixtures:MovieDetail',
            kwargs={'pk': movie_id}
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'fixtures:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(
            to=movie_detail_url
        )


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                'cannot change another '
                'users vote'
            )
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'fixtures:MovieDetail',
            kwargs={'pk': movie_id}
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'fixtures:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(
            to=movie_detail_url
        )

templates/fixtures/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

<!-- MAIN -->
{% block main %}
    {#    writers and actors    #}
    <div class="col">
        <h1>{{ object }}</h1>
        <p class="lead">
            {{ object.plot }}
        </p>
    </div>
    {#    images uploaded    #}
    <ul class="movie-image list-inline">
        {% for i in object.movieimage_set.all %}
            <li class="list-inline-item">
                <img alt="{{ object }}" src="{{ i.image.url }}">
            </li>
        {% endfor %}
    </ul>
    <p>Directed
        by {{ object.director }}
    </p>
{% endblock %}

<!-- SIDEBAR -->
{% block sidebar %}
    {#    movie rating  #}
    <div>
        This movie is rated:
        <span class="badge badge-primary">
            {{ object.get_rating_display }}
        </span>
    </div>

    {# image upload form #}
    {% if image_form %}
        <div>
            <h2>Upload New Image</h2>
            <form method="post"
                  enctype="multipart/form-data"
                  action="{% url 'fixtures:MovieImageUpload' movie_id=object.id %}">
                {% csrf_token %}
                {{ image_form.as_p }}
                <p>
                    <button class="btn btn-primary">
                        Upload
                    </button>
                </p>
            </form>
        </div>
    {% endif %}

    {#    movie score   #}
    <div>
        <h2>
            Score: {{ object.score|default_if_none:"TBD" }}
        </h2>
    </div>

    {#    voting form   #}
    <div>
        {% if vote_form %}
            <form method="post" action="{{ vote_form_url }}">
                {% csrf_token %}
                {{ vote_form.as_p }}
                <button class="btn btn-primary">
                    Vote
                </button>
            </form>
        {% else %}
            <p>Log in to vote for this.</p>
        {% endif %}
    </div>
{% endblock %}

templates/fixtures/movie_list.html
{% extends 'base.html' %}

{% block title %}
    Movie List Template
{% endblock %}

{% block main %}
    <ul>
        {% for movie in object_list %}
            <li>
                <a href="{% url 'fixtures:MovieDetail' pk=movie.id %}">{{ movie }}</a>
            </li>

        {% empty %}
            <li>
                No Movies Yet.
            </li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav>
            <ul class="pagination">
                <li class="page-item">
                    <a href="{% url 'fixtures:MovieList' %}?page=1" class="page-link"></a>
                </li>
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="{% url 'fixtures:MovieList' %}" class="page-link">
                            {{ page_obj.previous_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a href="{% url 'fixtures:MovieList' %}?page={{ page_obj.number }}" class="page-link">
                        {{ page_obj.number }}
                    </a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="{% url 'fixtures:MovieList' %}?page={{ page_obj.next_page_number }}" class="page-link">
                            {{ page_obj.next_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a href="{% url 'fixtures:MovieList' %}?page=last" class="page-link">
                        Last
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}
{% endblock %}

templates/fixtures/person_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.first_name }}
    {{ object.last_name }}
{% endblock %}

{% block main %}
<h1>{{ object }}</h1>
<h2>Actor</h2>
<ul>
    {% for role in object.role_set.all %}
        <li>
            <a href="{% url 'fixtures:MovieDetail' role.movie.id %}">
                {{ role.movie }}
            </a>
            {{ role.name }}
        </li>
    {% endfor %}
</ul>

<h2>Writer</h2>
<ul>
    {% for movie in object.writing_credits.all %}
        <li>
            <a href="{% url 'fixtures:MovieDetail' movie.id %}">
                {{ movie }}
            </a>
        </li>
    {% endfor %}
</ul>

<h2>Director</h2>
<ul>
    {% for movie in object.directed.all %}
        <li>
            <a href="{% url 'fixtures:MovieDetail' movie.id %}">
                {{ movie }}
            </a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

templates/fixtures/top_movies_list.html
{% extends "base.html" %}
{% load cache %}

{% block title %}
    Top 10 Movies
{% endblock %}

{% block main %}
    <h1>Top 10 Movies</h1>
    {% cache 300 TopMovies %}
    <ol>
        {% for movie in object_list %}
            <li>
                <a href="{% url 'fixtures:MovieDetail' pk=movie.id %}">
                    {{ movie }}
                </a>
            </li>
        {% endfor %}
    </ol>
    {% endcache %}
{% endblock %}