conf/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from fixtures.views import home_page

MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns = [
    # ADMIN / DEV
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),

    # PUBLIC
    path('', home_page, name="index"),
    path('movies/', include('fixtures.urls', namespace='fixtures')),

    # USER AUTH
    path('security/', include('security.urls', namespace='security')),
]
urlpatterns += MEDIA_FILE_PATHS

fixtures/urls.py
from django.urls import path

from fixtures.views import (
    MovieList, MovieDetail, TopMovies, UpdateVote, CreateVote, MovieImageUpload,
)

app_name = 'fixtures'
urlpatterns = [
    # Movie Views:
    path('movie',
         MovieList.as_view(),
         name='MovieList'),
    path('<int:pk>',
         MovieDetail.as_view(),
         name='MovieDetail'),
    path('top10/',
         TopMovies.as_view(),
         name='TopMovies'),


    # Vote Views
    path('<int:movie_id>/vote',
         CreateVote.as_view(),
         name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>',
         UpdateVote.as_view(),
         name='UpdateVote'),

    # Upload Views
    path('movie/<int:movie_id>/image/upload',
         MovieImageUpload.as_view(),
         name='MovieImageUpload'),

]

security/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from security import views

app_name = 'security'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

fixtures/views/base_views.py
# Author - Matt Andrzejczuk

# NO TEMPLATES:
from django.http import HttpResponse
from django.template import loader
# GENERIC:
from django.urls import reverse
from django.views.generic import (ListView, DetailView, )

from fixtures.forms import (VoteForm, MovieImageForm, )
from fixtures.mixins import CachePageVaryOnCookieMixin
from fixtures.models import (Movie, Vote, )

from pyink import ink




def home_page(request):
    template = loader.get_template("home_page.html")
    visitor = request.META
    context = {"visitor": visitor}
    return HttpResponse(template.render(context))


class MovieList(ListView):
    model = Movie
    paginate_by = 10
    # def get_context_data(self, object_list, **kwargs):
    #     ctx = super().get_context_data()
    #     ctx['user'] = self.request.user
    #     return ctx


class TopMovies(CachePageVaryOnCookieMixin, ListView):
    template_name = 'fixtures/top_movies_list.html'
    queryset = Movie.objects.top_movies(limit=10)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['user'] = self.request.user
        ink.p("TopMovies", ink.BG_PURPLE, ink.ENDC + "\n")
        return ctx

class MovieDetail(DetailView):
    queryset = (
        Movie.objects.all_with_related_persons_and_score()
    )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse(
                    'fixtures:UpdateVote',
                    kwargs={'movie_id': vote.movie.id,
                            'pk': vote.id}
                )
            else:
                vote_form_url = (
                    reverse(
                        'fixtures:CreateVote',
                        kwargs={'movie_id': self.object.id}
                    )
                )
            vote_form = VoteForm(instance=vote)
            image_form = self.movie_image_form()
            ctx['vote_form'] = vote_form
            ctx['image_form'] = image_form
            ctx['vote_form_url'] = vote_form_url
        return ctx

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Movie Database {% endblock %}</title>
    {#<link href="http://akveo.com/blur-admin/styles/app-bce21c2366.css" rel="stylesheet" crossorigin="anonymous">#}
    {#<link href="http://akveo.com/blur-admin/styles/vendor-2cae343ef1.css" rel="stylesheet" crossorigin="anonymous">#}

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="/resources/themes/DarkTemplar/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/resources/themes/DarkTemplar/favicon.png">

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet"/>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- Nucleo Icons -->
    <link href="/static/themes/DarkTemplar/css/nucleo-icons.css" rel="stylesheet"/>
    <!-- CSS Files -->
    <link href="/static/themes/DarkTemplar/css/black-dashboard.min.css" rel="stylesheet"/>

</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <div class="navbar-brand">Site Branding</div>

        </div>
        <ul class="nav nav-pills">
            {% if user.is_authenticated %}
                <li role="presentation">

                    <p class="navbar-text">
                        Logged in as {{ user.username }}.
                        <a href="{% url 'security:logout' %}" class="nav-link">
                            Logout here.
                        </a>
                    <p>
                </li>
            {% else %}
                <li role="presentation">
                    <a href="{% url 'security:login' %}" class="button btn btn-primary navbar-btn">
                        Sign in
                    </a>
                </li>
            {% endif %}
            <li role="presentation">
                <a class="button btn btn-info" href="{% url 'fixtures:MovieList' %}">Movies</a>
            </li>
            <li role="presentation">
                <a class="button btn btn-info" href="{% url 'fixtures:TopMovies' %}">
                    Top 10
                </a>
            </li>
        </ul>
    </div>
</nav>

<!--BLOCK FOR NAVIGATION-->
{% block navbar %}
{% endblock %}`

<div class="container">
    <div>
        <div class="row">
            <div class="col-sm-8">
                <!--BLOCK FOR BASE VIEWS-->
                {% block main %} {% endblock %}
            </div>
            <div class="col-sm-3 offset-sm-1">
                <!--BLOCK FOR SIDEBAR-->
                {% block sidebar %} {% endblock %}
            </div>
        </div>
    </div>
</div>


<!--BLOCK FOR EXTRA/FEATURED-->
<!--TODO: move this block to its own template-->


</body>
</html>

templates/home_page.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

<!-- MAIN -->
{% block main %}
    {{ visitor }}
    {% for key, value in visitor.items %}

        <table class="table table-striped table-dark">
            <thead>
            <tr>

            </tr>
            </thead>
        </table>
        <ul>
            <li class="list-inline-item">
                <i>
                    {{ key }}
                </i>
                <b>
                    {{ value }}
                </b>
            </li>
        </ul>

    {% endfor %}
{% endblock %}

<!-- SIDEBAR -->
{% block sidebar %}

{% endblock %}

<!--
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>
-->